version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    ports: ["5432:5432"]
    volumes: ["./.data/postgres:/var/lib/postgresql/data"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  api:
    build: ./apps/api
    env_file: .env
    depends_on: [postgres, redis]
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes: ["./apps/api:/code"]
    ports: ["8000:8000"]
  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports: ["5050:80"]
    depends_on: [postgres]
